# Generated by Django 5.0.3 on 2024-03-23 20:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='dj/'),
            preserve_default=False,
        ),
    ]
