# Generated by Django 5.0.3 on 2024-03-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dj', '0002_dj_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dj',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='dj_audio/'),
        ),
    ]
