# Generated by Django 5.0.3 on 2024-03-19 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Club', '0001_initial'),
        ('Dj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Club.club')),
                ('dj', models.ManyToManyField(to='Dj.dj')),
            ],
        ),
    ]
