# Generated by Django 5.0.3 on 2024-03-24 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='event/'),
            preserve_default=False,
        ),
    ]
