# Generated by Django 5.0.3 on 2024-03-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dj', '0002_dj_photo'),
        ('Event', '0002_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='dj',
            field=models.ManyToManyField(related_name='event', to='Dj.dj'),
        ),
    ]
